export const seedArticles = [
  {
    id: 'a1',
    title: 'Mastering Focus in a Noisy World',
    slug: 'mastering-focus-noisy-world',
    thumbnail_url: 'https://images.pexels.com/photos/7976204/pexels-photo-7976204.jpeg?auto=compress&cs=tinysrgb&w=800',
    excerpt: 'Practical, evidence-based tactics to protect your attention and reclaim deep work in an age of constant distraction.',
    read_minutes: 7,
    price_cents: 299,
    tips_count: 124,
    category: 'Productivity',
    content_html: '<h2>The Crisis of Attention</h2><p>In today\'s hyper-connected world, our attention is under constant siege. Every notification, email, and ping competes for a slice of our cognitive bandwidth.</p><h2>Building Focus Muscles</h2><p>Like physical fitness, mental focus requires consistent practice and the right techniques. Here are proven strategies to strengthen your concentration.</p><h3>1. Time Blocking</h3><p>Dedicate specific time blocks to deep work. During these periods, eliminate all distractions and focus on a single task.</p><h3>2. Digital Minimalism</h3><p>Audit your digital life. Remove apps and services that don\'t provide significant value to your life or work.</p><blockquote>The ability to perform deep work is becoming increasingly rare at exactly the same time it is becoming increasingly valuable in our economy.</blockquote><h3>3. Environmental Design</h3><p>Create a workspace that promotes focus. This might mean noise-cancelling headphones, a clean desk, or a dedicated office space.</p>',
  },
  {
    id: 'a2',
    title: 'Designing for Micro-Transactions',
    slug: 'designing-micro-transactions',
    thumbnail_url: 'https://images.pexels.com/photos/7947662/pexels-photo-7947662.jpeg?auto=compress&cs=tinysrgb&w=800',
    excerpt: 'Friction kills conversion—here\'s how to reduce it with intent-first UI patterns and psychology-driven design.',
    read_minutes: 5,
    price_cents: 0,
    tips_count: 89,
    category: 'Design',
    content_html: '<h2>The Friction Problem</h2><p>Every extra click, form field, or moment of confusion in a payment flow dramatically reduces conversion rates.</p><h2>Intent-First Design</h2><p>The key to successful micro-transaction design is understanding and respecting user intent. When someone decides to pay, make it effortless.</p><h3>One-Click Purchases</h3><p>Amazon popularized this pattern for a reason—it works. Store payment methods securely and allow instant purchases with a single confirmation.</p><h3>Clear Value Communication</h3><p>Users need to understand exactly what they\'re getting before they pay. Show value props clearly and concisely.</p><h3>Trust Signals</h3><p>Security badges, clear refund policies, and transparent pricing build the trust needed for quick purchase decisions.</p>',
  },
  {
    id: 'a3',
    title: 'The Creator Economy in 2025',
    slug: 'creator-economy-2025',
    thumbnail_url: 'https://images.pexels.com/photos/5561923/pexels-photo-5561923.jpeg?auto=compress&cs=tinysrgb&w=800',
    excerpt: 'How independent creators are building sustainable businesses through direct monetization and community-first strategies.',
    read_minutes: 8,
    price_cents: 499,
    tips_count: 203,
    category: 'Business',
    content_html: '<h2>The Shift to Direct Monetization</h2><p>Creators are moving away from ad-based revenue models toward direct relationships with their audiences.</p><h2>Multiple Revenue Streams</h2><p>Successful creators don\'t rely on a single income source. They diversify across tips, premium content, and community subscriptions.</p><h3>Tips as Social Currency</h3><p>Micro-tips have emerged as a powerful way for audiences to show appreciation without major financial commitment.</p><h3>Premium Content</h3><p>High-quality, in-depth content commands premium prices when it provides genuine value.</p><h3>Community Access</h3><p>Exclusive communities create ongoing relationships and recurring revenue.</p>',
  },
  {
    id: 'a4',
    title: 'Building Habits That Last',
    slug: 'building-habits-that-last',
    thumbnail_url: 'https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=800',
    excerpt: 'Science-backed strategies for creating lasting behavioral change without relying on willpower alone.',
    read_minutes: 6,
    price_cents: 0,
    tips_count: 156,
    category: 'Personal Growth',
    content_html: '<h2>The Habit Loop</h2><p>Every habit follows a simple loop: cue, routine, reward. Understanding this loop is key to building better habits.</p><h2>Start Small</h2><p>The biggest mistake people make is trying to change too much at once. Start with tiny, almost laughably small habits.</p><h3>Stack Your Habits</h3><p>Link new habits to existing ones. After I pour my coffee, I will meditate for 2 minutes.</p><h3>Make It Obvious</h3><p>Design your environment to make good habits the path of least resistance.</p><blockquote>You do not rise to the level of your goals. You fall to the level of your systems.</blockquote>',
  },
  {
    id: 'a5',
    title: 'The Future of Remote Work',
    slug: 'future-remote-work',
    thumbnail_url: 'https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=800',
    excerpt: 'Remote work is here to stay. Explore emerging trends and tools shaping the distributed workplace.',
    read_minutes: 9,
    price_cents: 399,
    tips_count: 178,
    category: 'Technology',
    content_html: '<h2>The Remote Revolution</h2><p>COVID-19 accelerated a trend that was already in motion. Remote work has proven to be not just viable but preferable for many knowledge workers.</p><h2>Async-First Communication</h2><p>The most successful remote teams prioritize asynchronous communication, respecting deep work time.</p><h3>Tools That Matter</h3><p>The right tools can make or break a remote team. Focus on tools that reduce friction rather than add complexity.</p><h3>Building Culture Remotely</h3><p>Culture doesn\'t require physical proximity, but it does require intentional effort.</p>',
  },
  {
    id: 'a6',
    title: 'Minimalist Living: A Practical Guide',
    slug: 'minimalist-living-guide',
    thumbnail_url: 'https://images.pexels.com/photos/1743165/pexels-photo-1743165.jpeg?auto=compress&cs=tinysrgb&w=800',
    excerpt: 'Declutter your space and mind with practical minimalism strategies that actually work in real life.',
    read_minutes: 7,
    price_cents: 0,
    tips_count: 92,
    category: 'Lifestyle',
    content_html: '<h2>What Minimalism Really Means</h2><p>Minimalism isn\'t about owning as little as possible. It\'s about making room for what matters by removing what doesn\'t.</p><h2>The KonMari Method</h2><p>Marie Kondo\'s approach asks one simple question: Does this spark joy? If not, thank it for its service and let it go.</p><h3>Digital Minimalism</h3><p>Our digital lives need decluttering too. Unsubscribe, unfollow, and delete ruthlessly.</p><h3>Mindful Consumption</h3><p>Before acquiring anything new, ask: Do I need this? Will it add value to my life?</p>',
  },
];

export const seedCommunities = [
  {
    id: 'c1',
    name: 'Deep Focus Lab',
    slug: 'deep-focus-lab',
    cover_url: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Evidence-based productivity strategies with weekly AMAs, accountability partners, and exclusive research deep-dives.',
    members_count: 1542,
    monthly_price_cents: 799,
  },
  {
    id: 'c2',
    name: 'Creator Growth Guild',
    slug: 'creator-growth-guild',
    cover_url: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Monetization playbooks, portfolio reviews, and direct feedback from creators earning 6-7 figures.',
    members_count: 832,
    monthly_price_cents: 999,
  },
  {
    id: 'c3',
    name: 'Design Systems Collective',
    slug: 'design-systems-collective',
    cover_url: 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'For designers building and scaling design systems. Share components, patterns, and lessons learned.',
    members_count: 645,
    monthly_price_cents: 1299,
  },
  {
    id: 'c4',
    name: 'Remote Work Pioneers',
    slug: 'remote-work-pioneers',
    cover_url: 'https://images.pexels.com/photos/4050315/pexels-photo-4050315.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Community for remote workers and digital nomads. Tips, tools, and travel recommendations from around the world.',
    members_count: 2134,
    monthly_price_cents: 599,
  },
];
